# This workflow will build a Java Project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build

  deploy-to-tomcat:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 14]
        tomcat: [9.0.37, 8.5.57]
    env: 
      TOMCAT_VERSION: ${{ matrix.tomcat }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Prepare Tomcat ${{ matrix.tomcat }}
        run: |
          wget https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_VERSION:0:1}/v${{ matrix.tomcat }}/bin/apache-tomcat-${{ matrix.tomcat }}.zip
          unzip apache-tomcat-${{ matrix.tomcat }}.zip
          chmod a+x apache-tomcat-${{ matrix.tomcat }}/bin/*.sh
          apache-tomcat-${{ matrix.tomcat }}/bin/catalina.sh start
      - name: Build with Gradle
        run: ./gradlew bootWar
      - name: Deploy to Tomcat
        run: cp build/libs/joinfaces-gradle-war-example.war apache-tomcat-${{ matrix.tomcat }}/webapps/
      - name: Verify Deployment
        run: |
          timeout --preserve-status 60s tail -f apache-tomcat-${{ matrix.tomcat }}/logs/catalina.out || true
          wget localhost:8080/joinfaces-gradle-war-example/index.xhtml
          grep "Hello from Spring" index.xhtml
